# Generated by Django 5.1.2 on 2024-12-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0002_customuser_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='test_field',
        ),
    ]
