# Generated by Django 5.1.2 on 2024-12-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0003_remove_customuser_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresa',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='data_nasterii',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='newsletter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oras',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
